[tool.poetry]
name = "factfinder"
version = "0.1.1"
description = "Library for city events analysis from social media posts and comments"
authors = ["sandrro, georgekontsevik, eloktev, mvin8, pacificus"]
readme = "README.rst"
packages = [{ include = "factfinder" }]

[tool.poetry.dependencies]
python = "^3.8.1"
pandas = "^1.5.3"
matplotlib = "^3.7.0"
seaborn = "^0.12.2"
nltk = "^3.8.1"
scikit-learn = "^1.2.1"
spacy = "^3.5.0"
fuzzywuzzy = "^0.18.0"
geopandas = "^0.12.2"
numpy = "^1.24.3"
flair = "^0.12.2"
networkx = "^3.1"
osm2geojson = "^0.2.3"
osmnx = "^1.5.1"
pymorphy2 = "^0.9.1"
pymorphy2-dicts-ru = "^2.4.417127.4579844"
torch = "^2.0.1"
tqdm = "^4.64.1"
geopy = "^2.3.0"
shapely = "^2.0.1"
transformers = "^4.28.1"
bertopic = "^0.15.0"
sphinx = "^7.1.2"
sphinx-rtd-theme = "^1.3.0rc1"
autodocsumm = "^0.2.11"

flake8 = "^6.0.0"
isort = "^5.12.0"
black = "^23.1.0"
pylint = "^3.0.2"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80

[tool.isort]
profile = 'black'
line_length = 80
